### ISSUE TITLE
User profiles / Use cases / Components

### ISSUE THREAD

**Issue by anhourandaquarter** [anhourandaquarter/carmina#10]
## User profiles

We'll aim to have at least 5 per contributor, for a total of 20. Let's have these in the `/user-stories` folder by Thursday, Nov. 14.

## Use cases

We can create one use case per user profile. These will also be in the `/user-stories` folder by Thursday, Nov. 14.

## Components

Since our project is not that large, let's come up with at least 1 per contributor. The `user-stories/components.md` file has some suggestions to start out. Complete these by Thursday, Nov. 14.

**Comment by anhourandaquarter** [comment]
I've added my own user/use cases and filled out the **Language verification** and **Scansion function** components

**Comment by dacb** [comment]
Can you revisit these and combine the user stories into one doc and the components in another?

**Comment by thatswhatsimonsaid** [comment]
I've revisited the documents. The user stories and and components are already in separate documents.

**Comment by anhourandaquarter** [comment]
@thatswhatsimonsaid I think @dacb means that we should put the stories currently in `chan.md`, `choi.md`, and `nova.md` into `user_stories.md` instead of having them in separate documents.

**Comment by anhourandaquarter** [comment]
I can get on this after class today

**Comment by anhourandaquarter** [comment]
Delegating to @Emend026

**Comment by dacb** [comment]
That makes sense to me!



--
David A. C. Beck, Ph.D.
***@***.******@***.***>
Research Associate Professor, Dept. of Chemical Engineering
Director, Scientific Software Engineering Center
Director of Research & Senior Data Science Fellow - eScience Institute
Adjunct Research Associate Professor of Paul G. Allen School of Computer Science & Engineering
Adjunct Research Associate Professor, Env. and Occ. Health Sciences

The University of Washington acknowledges the Coast Salish peoples of this land, the land which touches the shared waters of all tribes and bands within the Suquamish, Tulalip and Muckleshoot nations.  (More information available here<https://www.washington.edu/diversity/tribal-relations/>.)


________________________________

**Comment by anhourandaquarter** [comment]
Closing this issue after @Emend026 's last update in `user-stories`
