### ISSUE TITLE
Functions in parser.py

### ISSUE THREAD

**Issue by anhourandaquarter** [anhourandaquarter/carmina#16]
`parser.py` is the module that contains our functions for reading in and normalizing textual input from `.txt` or `.xml` files. There are three functions that we are working on:

## parse_txt
Takes in a `.txt` file, reads using base Python `with open(...)` syntax, and 

## normalize_line

**Comment by anhourandaquarter** [comment]
We will be working on the `16-parser` branch.

**Comment by Emend026** [comment]
Hi guys. I added some changes to the parser.py normalized_lines function. Please check it out. I'm not too sure how to check if it does work with the xml. files. but please let me know so I can make changes
