### ISSUE TITLE
Test functions for parser.py

### ISSUE THREAD

**Issue by anhourandaquarter** [anhourandaquarter/carmina#18]

**Comment by anhourandaquarter** [comment]
@thatswhatsimonsaid What's your status on your TODOs?

**Comment by thatswhatsimonsaid** [comment]
I've committed it

**Comment by anhourandaquarter** [comment]
I don't see the changes on 18-test-functions-for-parserpy. Did you make a new branch?

**Comment by anhourandaquarter** [comment]
@thatswhatsimonsaid looks like you were working on your own branch for this. Please merge your changes to `main` and make sure to work on the branches specific to the issue in the future.
