### ISSUE TITLE
Technology review

### ISSUE THREAD

**Issue by anhourandaquarter** [anhourandaquarter/carmina#9]
### Discussed in https://github.com/anhourandaquarter/carmina/discussions/8

<div type='discussions-op-text'>

<sup>Originally posted by **anhourandaquarter** November  7, 2024</sup>
In preparation for our technology review presentation on Tuesday, I figured we can start a thread here.

Topics:
- Classical Latin (`cltk`)
- String parsing
- Text analysis
- Web parsing (`selenium`, `requests`, `beautifulSoup`) -- for getting to Logeion if we want to use it to verify Latin text.

I can look into `cltk`. Let's look at some other packages for string parsing and/or text analysis. I can think of `nltk`, `TextBlob`, and `spaCy`, though there might be others. </div>

**Comment by hhchan94** [comment]
I can do `spaCy` and @Emend026  is going to take a look at `nltk`. So maybe @thatswhatsimonsaid  can work on `TextBlob`.

**Comment by anhourandaquarter** [comment]
Sweet. I think we only need three technologies. Let's go ahead and each work on our own slide, then consolidate before class.

**Comment by anhourandaquarter** [comment]
@hhchan94 I liked the format of your slide! Hope it's OK to update mine to match : )

**Comment by thatswhatsimonsaid** [comment]
on it!!

**Comment by anhourandaquarter** [comment]
Presentation's done, so I'll go ahead and close this issue. 

Summary. Neither nltk nor spaCy really provide the flexibility and parsing that we need for processing Latin. cltk would be best for us, but it has a lot of dependencies that might be difficult to work with. For our first milestone, it's likely we won't have to use any of these at all.
